export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT_DISH';
export const GET_RESTAURANT_BY_ID = 'GET_RESTAURANT_BY_ID';
export const DELETE_RESTAURANT_DISH = 'DELETE_RESTAURANT_DISH';

export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const PLACE_ORDER = 'PLACE_ORDER';
export const DIFF_RESTAURANT_ERROR = 'DIFF_RESTAURANT_ERROR';

export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE'

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART'

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const GET_RESTAURANT_DASHBOARD = 'GET_RESTAURANT_DASHBOARD'
export const UPDATE_RESTAURANT_DASHBOARD = 'UPDATE_RESTAURANT_DASHBOARD'

export const FETCH_RESTAURANT_ORDERS_REQUEST = 'FETCH_RESTAURANT_ORDERS_REQUEST'
export const FETCH_RESTAURANT_ORDERS_SUCCESS = 'FETCH_RESTAURANT_ORDERS_SUCCESS'
export const FETCH_RESTAURANT_ORDERS_FAILURE = 'FETCH_RESTAURANT_ORDERS_FAILURE'
export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST'
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS'
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE'

export const FETCH_RESTAURANT_DASHBOARD_REQUEST = 'FETCH_RESTAURANT_DASHBOARD_REQUEST'
export const UPDATE_RESTAURANT_DASHBOARD_REQUEST = 'UPDATE_RESTAURANT_DASHBOARD_REQUEST'

export const UPDATE_RESTAURANT_DASHBOARD_SUCCESS = 'FETCH_REUPDATE_RESTAURANT_DASHBOARD_SUCCESS'
export const UPDATE_RESTAURANT_DASHBOARD_FAILURE = 'UPDATE_RESTAURANT_DASHBOARD_FAILURE'

export const FETCH_RESTAURANT_DASHBOARD_SUCCESS = 'FETCH_RESTAURANT_DASHBOARD_SUCCESS'
export const FETCH_RESTAURANT_DASHBOARD_FAILURE = 'FETCH_RESTAURANT_DASHBOARD_FAILURE'

export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE'





